"""add range sessions

Revision ID: 3ca46faf814f
Revises: bb79ac38448f
Create Date: 2026-09-22 05:30:23.257685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca46faf814f'
down_revision: Union[str, Sequence[str], None] = 'bb79ac38448f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('range_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('occurred_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_range_sessions_occurred_date'), 'range_sessions', ['occurred_date'], unique=False)
    op.create_index(op.f('ix_range_sessions_owner_id'), 'range_sessions', ['owner_id'], unique=False)
    op.create_table('range_session_firearms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('range_session_id', sa.UUID(), nullable=False),
    sa.Column('firearm_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firearm_id'], ['firearms.id'], ),
    sa.ForeignKeyConstraint(['range_session_id'], ['range_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('range_session_id', 'firearm_id', name='uq_range_session_firearm')
    )
    op.create_index(op.f('ix_range_session_firearms_firearm_id'), 'range_session_firearms', ['firearm_id'], unique=False)
    op.create_index(op.f('ix_range_session_firearms_range_session_id'), 'range_session_firearms', ['range_session_id'], unique=False)
    op.create_table('range_session_ammo_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('range_session_firearm_id', sa.UUID(), nullable=False),
    sa.Column('ammo_lot_id', sa.UUID(), nullable=True),
    sa.Column('inventory_transaction_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.Enum('inventory', 'other', name='range_ammo_source_type'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ammo_lot_id'], ['ammo_lots.id'], ),
    sa.ForeignKeyConstraint(['inventory_transaction_id'], ['ammo_inventory_transactions.id'], ),
    sa.ForeignKeyConstraint(['range_session_firearm_id'], ['range_session_firearms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_range_session_ammo_usage_ammo_lot_id'), 'range_session_ammo_usage', ['ammo_lot_id'], unique=False)
    op.create_index(op.f('ix_range_session_ammo_usage_inventory_transaction_id'), 'range_session_ammo_usage', ['inventory_transaction_id'], unique=False)
    op.create_index(op.f('ix_range_session_ammo_usage_range_session_firearm_id'), 'range_session_ammo_usage', ['range_session_firearm_id'], unique=False)
    op.create_index(op.f('ix_range_session_ammo_usage_source_type'), 'range_session_ammo_usage', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_range_session_ammo_usage_source_type'), table_name='range_session_ammo_usage')
    op.drop_index(op.f('ix_range_session_ammo_usage_range_session_firearm_id'), table_name='range_session_ammo_usage')
    op.drop_index(op.f('ix_range_session_ammo_usage_inventory_transaction_id'), table_name='range_session_ammo_usage')
    op.drop_index(op.f('ix_range_session_ammo_usage_ammo_lot_id'), table_name='range_session_ammo_usage')
    op.drop_table('range_session_ammo_usage')
    op.drop_index(op.f('ix_range_session_firearms_range_session_id'), table_name='range_session_firearms')
    op.drop_index(op.f('ix_range_session_firearms_firearm_id'), table_name='range_session_firearms')
    op.drop_table('range_session_firearms')
    op.drop_index(op.f('ix_range_sessions_owner_id'), table_name='range_sessions')
    op.drop_index(op.f('ix_range_sessions_occurred_date'), table_name='range_sessions')
    op.drop_table('range_sessions')
    # ### end Alembic commands ###
