"""initial schema

Revision ID: 56fb742d4bdf
Revises: 
Create Date: 2026-09-21 05:10:10.100209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56fb742d4bdf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_selectable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibers_name'), 'calibers', ['name'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'defunct', 'unknown', name='organization_status'), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('oidc_subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_oidc_subject'), 'users', ['oidc_subject'], unique=True)
    op.create_table('ammo_brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manufacturer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manufacturer_id', 'name', name='uq_ammo_brand_manufacturer_name')
    )
    op.create_index(op.f('ix_ammo_brands_manufacturer_id'), 'ammo_brands', ['manufacturer_id'], unique=False)
    op.create_index(op.f('ix_ammo_brands_name'), 'ammo_brands', ['name'], unique=False)
    op.create_table('caliber_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caliber_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['caliber_id'], ['calibers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias', name='uq_caliber_alias')
    )
    op.create_index(op.f('ix_caliber_aliases_caliber_id'), 'caliber_aliases', ['caliber_id'], unique=False)
    op.create_table('firearms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('manufacturer_id', sa.UUID(), nullable=True),
    sa.Column('caliber_id', sa.UUID(), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('firearm_type', sa.Enum('handgun', 'rifle', 'shotgun', 'receiver', 'other', 'unknown', name='firearm_type'), nullable=False),
    sa.Column('manufacture_date_from', sa.Date(), nullable=True),
    sa.Column('manufacture_date_to', sa.Date(), nullable=True),
    sa.Column('manufacture_date_confidence', sa.Enum('exact', 'year', 'estimated', 'unknown', name='manufacture_date_confidence'), nullable=False),
    sa.Column('status', sa.Enum('owned', 'sold', 'transferred', 'stolen', 'lost', 'destroyed', 'other', name='firearm_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caliber_id'], ['calibers.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firearms_caliber_id'), 'firearms', ['caliber_id'], unique=False)
    op.create_index(op.f('ix_firearms_manufacturer_id'), 'firearms', ['manufacturer_id'], unique=False)
    op.create_index(op.f('ix_firearms_owner_id'), 'firearms', ['owner_id'], unique=False)
    op.create_table('manufacturer_profiles',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('is_selectable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('organization_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('related_organization_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('owned_by', 'subsidiary_of', 'brand_of', 'successor_to', 'predecessor_of', 'acquired_by', name='organization_relationship_type'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['related_organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'related_organization_id', 'relationship_type', 'effective_from', name='uq_organization_relationship')
    )
    op.create_index(op.f('ix_organization_relationships_organization_id'), 'organization_relationships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_relationships_related_organization_id'), 'organization_relationships', ['related_organization_id'], unique=False)
    op.create_table('ammo_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('caliber_id', sa.UUID(), nullable=False),
    sa.Column('grain_weight', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('projectile_type', sa.String(length=100), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('manufacturer_sku', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['ammo_brands.id'], ),
    sa.ForeignKeyConstraint(['caliber_id'], ['calibers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ammo_products_brand_id'), 'ammo_products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_ammo_products_caliber_id'), 'ammo_products', ['caliber_id'], unique=False)
    op.create_index(op.f('ix_ammo_products_projectile_type'), 'ammo_products', ['projectile_type'], unique=False)
    op.create_table('ammo_lots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('ammo_product_id', sa.UUID(), nullable=False),
    sa.Column('lot_number', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ammo_product_id'], ['ammo_products.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ammo_lots_ammo_product_id'), 'ammo_lots', ['ammo_product_id'], unique=False)
    op.create_index(op.f('ix_ammo_lots_lot_number'), 'ammo_lots', ['lot_number'], unique=False)
    op.create_index(op.f('ix_ammo_lots_owner_id'), 'ammo_lots', ['owner_id'], unique=False)
    op.create_table('ammo_inventory_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ammo_lot_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.Enum('acquired', 'expended', 'given', 'sold', 'quarantined', 'released', 'returned', 'disposed', 'adjustment_in', 'adjustment_out', name='ammo_transaction_type'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ammo_lot_id'], ['ammo_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ammo_inventory_transactions_ammo_lot_id'), 'ammo_inventory_transactions', ['ammo_lot_id'], unique=False)
    op.create_index(op.f('ix_ammo_inventory_transactions_occurred_at'), 'ammo_inventory_transactions', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_ammo_inventory_transactions_transaction_type'), 'ammo_inventory_transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ammo_inventory_transactions_transaction_type'), table_name='ammo_inventory_transactions')
    op.drop_index(op.f('ix_ammo_inventory_transactions_occurred_at'), table_name='ammo_inventory_transactions')
    op.drop_index(op.f('ix_ammo_inventory_transactions_ammo_lot_id'), table_name='ammo_inventory_transactions')
    op.drop_table('ammo_inventory_transactions')
    op.drop_index(op.f('ix_ammo_lots_owner_id'), table_name='ammo_lots')
    op.drop_index(op.f('ix_ammo_lots_lot_number'), table_name='ammo_lots')
    op.drop_index(op.f('ix_ammo_lots_ammo_product_id'), table_name='ammo_lots')
    op.drop_table('ammo_lots')
    op.drop_index(op.f('ix_ammo_products_projectile_type'), table_name='ammo_products')
    op.drop_index(op.f('ix_ammo_products_caliber_id'), table_name='ammo_products')
    op.drop_index(op.f('ix_ammo_products_brand_id'), table_name='ammo_products')
    op.drop_table('ammo_products')
    op.drop_index(op.f('ix_organization_relationships_related_organization_id'), table_name='organization_relationships')
    op.drop_index(op.f('ix_organization_relationships_organization_id'), table_name='organization_relationships')
    op.drop_table('organization_relationships')
    op.drop_table('manufacturer_profiles')
    op.drop_index(op.f('ix_firearms_owner_id'), table_name='firearms')
    op.drop_index(op.f('ix_firearms_manufacturer_id'), table_name='firearms')
    op.drop_index(op.f('ix_firearms_caliber_id'), table_name='firearms')
    op.drop_table('firearms')
    op.drop_index(op.f('ix_caliber_aliases_caliber_id'), table_name='caliber_aliases')
    op.drop_table('caliber_aliases')
    op.drop_index(op.f('ix_ammo_brands_name'), table_name='ammo_brands')
    op.drop_index(op.f('ix_ammo_brands_manufacturer_id'), table_name='ammo_brands')
    op.drop_table('ammo_brands')
    op.drop_index(op.f('ix_users_oidc_subject'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_calibers_name'), table_name='calibers')
    op.drop_table('calibers')
    # Drop PostgreSQL enum types created by this migration.
    sa.Enum(name='ammo_transaction_type').drop(
        op.get_bind(),
        checkfirst=True,
    )
    sa.Enum(name='organization_relationship_type').drop(
        op.get_bind(),
        checkfirst=True,
    )
    sa.Enum(name='firearm_status').drop(
        op.get_bind(),
        checkfirst=True,
    )
    sa.Enum(name='manufacture_date_confidence').drop(
        op.get_bind(),
        checkfirst=True,
    )
    sa.Enum(name='firearm_type').drop(
        op.get_bind(),
        checkfirst=True,
    )
    sa.Enum(name='organization_status').drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
