"""add accessories

Revision ID: bb79ac38448f
Revises: 02e700ff54f3
Create Date: 2026-09-22 02:19:35.404176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb79ac38448f'
down_revision: Union[str, Sequence[str], None] = '02e700ff54f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('manufacturer_id', sa.UUID(), nullable=True),
    sa.Column('firearm_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_location', sa.String(length=255), nullable=True),
    sa.Column('storage_location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firearm_id'], ['firearms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessories_firearm_id'), 'accessories', ['firearm_id'], unique=False)
    op.create_index(op.f('ix_accessories_manufacturer_id'), 'accessories', ['manufacturer_id'], unique=False)
    op.create_index(op.f('ix_accessories_owner_id'), 'accessories', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accessories_owner_id'), table_name='accessories')
    op.drop_index(op.f('ix_accessories_manufacturer_id'), table_name='accessories')
    op.drop_index(op.f('ix_accessories_firearm_id'), table_name='accessories')
    op.drop_table('accessories')
    # ### end Alembic commands ###
