"""add organization aliases

Revision ID: c9b7b47cd357
Revises: 56fb742d4bdf
Create Date: 2026-09-21 13:07:55.973640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9b7b47cd357'
down_revision: Union[str, Sequence[str], None] = '56fb742d4bdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'alias', name='uq_organization_aliases_organization_alias')
    )
    op.create_index(op.f('ix_organization_aliases_alias'), 'organization_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_organization_aliases_organization_id'), 'organization_aliases', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_aliases_organization_id'), table_name='organization_aliases')
    op.drop_index(op.f('ix_organization_aliases_alias'), table_name='organization_aliases')
    op.drop_table('organization_aliases')
    # ### end Alembic commands ###
